# Allocate additional memory to the Gradle JVM. The default is often not enough to decompile Minecraft.
org.gradle.jvmargs=-Xmx2G

# Various flags to optimize Gradle performance.
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configureondemand=true

# Enable all Gradle warnings
org.gradle.warning.mode=all

# Mod Metadata
group=ink.quietly
user=iridith
slug=elementary-archery
modId=elementary_archery
modName=Elementary Archery
modDescription=a simple archery mod with some elemental arrows and other things
authors=iridith
contributors=
license=MIT
# Mod Version
modVersion=0.1.0
# Branch Metadata
branchName=fabric-26.1
compatibleVersions=26.1
compatibleLoaders=fabric
